packages:
  - "apps/*"
  - "server"

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  - '@eslint/plugin-kit@0.7.2'
  - eslint@10.4.1
  - ts-loader@9.6.0
