packages:
  - "apps/*"
  - "server"

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  - '@eslint/plugin-kit@0.7.2'
  - eslint@10.4.1 || 10.9.1
  - ts-loader@9.6.0
  - '@nestjs/common@11.2.2'
  - '@nestjs/core@11.2.2'
  - '@nestjs/platform-express@11.2.2'
  - '@nestjs/testing@11.2.2'
  - '@types/node@26.3.0'
  - '@typescript-eslint/eslint-plugin@8.68.0'
  - '@typescript-eslint/parser@8.68.0'
  - '@typescript-eslint/project-service@8.68.0'
  - '@typescript-eslint/scope-manager@8.68.0'
  - '@typescript-eslint/tsconfig-utils@8.68.0'
  - '@typescript-eslint/type-utils@8.68.0'
  - '@typescript-eslint/types@8.68.0'
  - '@typescript-eslint/typescript-estree@8.68.0'
  - '@typescript-eslint/utils@8.68.0'
  - '@typescript-eslint/visitor-keys@8.68.0'
  - typescript-eslint@8.68.0
